### ISSUE TITLE
Nil pointer error is occurred when running without root permission

### ISSUE THREAD

**Issue by jollaman999** [hcloud-classic/hcc-piano#2]
The module is dead with nil pointer error when running without root permission.
It seems there is a bug in logger library.

@hcloudclassic

**Comment by hcloudclassic** [comment]
@jollaman999 The issue is fixed in https://github.com/hcloud-classic/hcc-piano/commit/3511cf6bfc82d27645d17063cc810cf907ec90ea. Thanks.
